### ISSUE TITLE
Collect the data source Microsoft Entra ID sign-in logs

### ISSUE THREAD

**Issue by Zawadidone** [invictus-ir/Microsoft-Extractor-Suite#101]
It would be nice if the tool is able to collect Microsoft Entra ID sign-in logs.

## References
* [https://learn.microsoft.com/en-us/entra/identity/monitoring-health/concept-sign-ins](https://learn.microsoft.com/en-us/entra/identity/monitoring-health/concept-sign-ins)

**Comment by JoeyInvictus** [comment]
Hi! Our tool supports acquiring Entra Sign-In logs through two methods! If you prefer using the `AzureADPreview` module, you can use `Get-ADSignInLogs`. If like `Graph` more, you can retrieve them using `Get-ADSignInLogsGraph`.

You can find our documentation and an overview of all the log sources collected by the tool here:
https://microsoft-365-extractor-suite.readthedocs.io/en/latest/

**Comment by Zawadidone** [comment]
Ah nice I misread the documentation because of the new name of Azure AD, thanks!

**Comment by JoeyInvictus** [comment]
Made a note to update the names to Entra ID in the next update :)
