### ISSUE TITLE
Get Azure Sign In logs and Admin Audit logs

### ISSUE THREAD

**Issue by Anny212** [invictus-ir/Microsoft-Extractor-Suite#108]
Hi,
I’ve been using this tool as usual, and it’s awesome!

However, in the latest version (V2.1.1), the extraction of Sign-In logs and Admin Audit logs failed. I tested it across several environments with different license levels.  

For Sign-In logs:
I connect to AzureAZ and then execute the Get-ADSignInLogs command. It attempts to extract the logs, but after three attempts, it says there are no logs, even though there are Sign-In logs visible in the Azure portal.
![image](https://github.com/user-attachments/assets/6184e459-6472-463e-96b4-e8510453243a)

For Admin Audit logs:
I connect to M365 and then execute the Get-AdminAuditLog command. I receive the following error:
![image](https://github.com/user-attachments/assets/6f0dfe41-c7ca-48b3-95da-69e3240b9d62)

If anyone has encountered similar issues or has any insights, I’d really appreciate your input! I’d be happy to help troubleshoot or share more details about my setup if needed.

**Comment by InfoSecGeoff** [comment]
I started experiencing this on 11/25 around noon when I started receiving 503s and other server side errors when pulling audit, sign in, and UAL logs along with this vague error you have posted. I tried the Graph and non-Graph options to no success. I chalked this up to the widespread Outlook outages that were happening at the time. These errors subsided but I have been unable to pull any UAL, sign in, and audit logs using Graph since. Information is visible in the 365 consoles to me as well. I tried HAWK and Search-UnifiedAuditLog from the Exchange Online module and also retrieved nothing. I have tested in 5+ tenants with varying levels of licensing to no success.

**Comment by JoeyInvictus** [comment]
Hi, glad you like the script! I had the same errors yesterday. @Anny212 are you still having those issues?

**Comment by Anny212** [comment]
Hi, @JoeyInvictus yes

**Comment by JoeyInvictus** [comment]
@Anny212, for the `Get-ADSignInLogs`, it looks like you are not connected or don't have the necessary permissions, as it returns an error to `connect to the Connect-AzureAD module`.

To connect to the Azure AD module, run:
`Connect-AzureAD`

Check if the `Get-AzureADAuditSignInLogs` Cmdlet is Available
You can verify if the `Get-AzureADAuditSignInLogs` cmdlet is available by using the following command:
`Get-Command -Name Get-AzureADAuditSignInLogs`

This should show you:

![image](https://github.com/user-attachments/assets/9f15974c-b8bd-404a-84f3-0eabea011ac9)

As an alternative, you can also try collecting the sign-in logs using the Graph PowerShell module. First, connect with an account that has the correct permissions by running:
`Get-ADSignInLogsGraph`

For the `Get-AdminAuditLog`, we use the `Search-AdminAuditLog` cmdlet, which is currently deprecated. We accepted a pull request this week that fixes this script, but we’re not sure if you already have the updated version. We will push it to the gallery and release page with our next update.

The new way to retrieve the Admin logs is by running:
`Search-UnifiedAuditLog -RecordType 'ExchangeAdmin'`

However, as @InfoSecGeoff  mentioned, there have been some known issues causing service-side errors when using Microsoft's APIs. Unfortunately, there isn't much we can do about these issues, as they are related to Microsoft's backend.

**Comment by Anny212** [comment]
Ok 
The Get-AzureADAuditSignInLogs command is available. I connect using the Connect-AzureAD command, then execute the Get-ADSignInLogs command, and now I get this error:
<img width="963" alt="image" src="https://github.com/user-attachments/assets/55ef724e-6c66-467c-806f-16a8d0886f56">
Is extracting Sign-In logs via the API available only with a premium license?

**Comment by JoeyInvictus** [comment]
This error occurs because the `Get-AzureADAuditSignInLogs` cmdlet requires Azure AD Premium P1 or P2 licensing to access sign-in logs. What license does the environment have where you trying to pull the logs from?

**Comment by JoeyInvictus** [comment]
I'm not entirely sure, to be honest. Perhaps you could forward it to Log Analytics and use the API to retrieve the data from there. I don't have much experience with accessing sign-in logs from the free tier.

Could you check if `Get-MgAuditLogSignIn` works with the free tier?

**Comment by Anny212** [comment]
@JoeyInvictus It seems that it also does not work with the free tier:(

**Comment by JoeyInvictus** [comment]
@Anny212 I'm not sure what environment you're using (client vs test), but it might be worth getting the P1/P2 trial license. It shouldn't cost anything as long as you cancel on time.
