### ISSUE TITLE
[WARNING] You must call Connect-Azure before running this script after successfully connecting to the Azure AD tenant

### ISSUE THREAD

**Issue by AnthoLaMalice** [invictus-ir/Microsoft-Extractor-Suite#13]
Dear, 

I am facing a problem when I try to use your tool to extract AAD sign in logs.

After "successfully" connecting to my Azure AD tenant, the tool still tells me that I need to call Connect-Azure.

However, I can't be sure that I've successfully logged in, because after entering the valid credentials, there's nothing displayed.

Is there some kind of verbose that could help me understand what's wrong? 
![image](https://github.com/invictus-ir/Microsoft-Extractor-Suite/assets/78861013/822934a1-c75e-4b14-a391-a79e214b5208)

I also tried using the Connect-M365 cmdlet to retrieve all the MailboxRules and it worked, so I think the problem is only with Connect-Azure.
![image](https://github.com/invictus-ir/Microsoft-Extractor-Suite/assets/78861013/9e8f660f-613d-4937-a070-9b7b515beda1)

Kind regards

**Comment by invictus-ir** [comment]
Hi there, thanks for reaching out sorry to hear that it's not working. It might have something to do with the Azure AD module, because it needs a specific version. In order to test if you have access to the right modules can you do:
- Connect-Azure
- After you've connected try running Get-AzureADAuditSignInLogs 
- This is the underlying cmdlet that is used to retrieve the SignInLogs. 
Let me know what you get back.

**Comment by AnthoLaMalice** [comment]
Indeed it was not installed. However it did not fix the issue :/ 
![image](https://github.com/invictus-ir/Microsoft-Extractor-Suite/assets/78861013/abc8a274-77fe-4898-b105-1ebc65cf7860)

**Comment by invictus-ir** [comment]
Ok please run the command Get-AzureADAuditSignInLogs and share the output

**Comment by invictus-ir** [comment]
Ok sometimes there are issues when using the normal AzureAD module and the preview one. We've had a similar issue https://github.com/invictus-ir/Microsoft-Extractor-Suite/issues/6 please follow the steps to test. 
Before you do so please exit out of the current session and start a brand new one. Then make sure the AzureADPreview module is available and last but not least check the commands inside the AzureADPreview module to make sure you can call(Get-AzureADAuditSignInLogs).

**Comment by JoeyInvictus** [comment]
Hi @AnthoLaMalice, Have you managed to get it working?
