### ISSUE TITLE
Suggestion: display timestamps in ISO8601 (and with timezone information) 

### ISSUE THREAD

**Issue by Qazeer** [invictus-ir/Microsoft-Extractor-Suite#14]
Hi!

If only a day is specified, as `StartDate` and `EndDate`, PowerShell will initialize the corresponding `DateTime` objects at 12:00 AM (midnight) in the system local timezone (whereas records in the `UAL` are stored in `UTC`). The results retrieved by `Search-UnifiedAuditLog` will thus be bound by the local system timezone.

This can be worked around by specifying a timezone in the `StartDate` and `EndDate` timestamps, or by directly providing timestamps in `UTC`, so not really an issue. However, it would be nice to display timezone information in the printed messages to disclose this specificity to the user.

Printing timestamps in the `ISO8601` format directly in `UTC` would have the additional benefit of standardization. This can be achieved with:

```powershell
"[...] between $($currentStart.ToUniversalTime().ToString("yyyy-MM-ddTHH:mm:ssK")) and $($currentEnd.ToUniversalTime().ToString("yyyy-MM-ddTHH:mm:ssK"))"
```

To illustrate a bit more, using `Get-UALAll -StartDate 2023-06-01 -EndDate 2023-06-10` on a system in `UTC-7` will result in the retrieval of records starting from `2023-06-01 07:00:00Z`.
So printing something like:
![image](https://github.com/invictus-ir/Microsoft-Extractor-Suite/assets/5614972/c08f1fed-91ed-4bf0-8907-8d5cb06e323f)
rather than:
![image](https://github.com/invictus-ir/Microsoft-Extractor-Suite/assets/5614972/c4fe991b-fa1d-4a48-a2b2-8f9fe5195fab)
would imho help clarify the timeframes for the records retrieved.

I can do a PR if you think the change is worthwhile.

**Comment by invictus-ir** [comment]
Hi that sounds like an excellent suggestion. A PR would be perfect, thank you!

**Comment by JoeyInvictus** [comment]
Thank you @Qazeer for your contribution, we have accepted your pull request and are looking at the other suggestions made.
