### ISSUE TITLE
Suggestion: increase the levels of depth for ConvertTo-Json

### ISSUE THREAD

**Issue by Qazeer** [invictus-ir/Microsoft-Extractor-Suite#17]
Hey!

By default `ConvertTo-Json` only convert nested objects to two levels, potentially resulting in data loss and more limited parsing of the results. This depth can be increased with `-Depth`.

For example for AAD sign-in logs:

```
"NetworkLocationDetails":  [
  "class SignInAuditLogObjectNetworkLocationDetails {\n  NetworkType: trustedNamedLocation\n  NetworkNames: System.Collections.Generic.List`1[System.String]\n}\n"
]
```

Additional suggestions:
  - Convert `ActivityDateTime` in `Get-ADAuditLogs` to ISO8601 format (instead of relying on the system locals).
  - Add a `Compress` flag for cmdlets that use `ConvertTo-Json`, to compress JSON results and facilitate parsing (with tools that work on compressed JSON objects).

I can do a PR for all three suggestions if needed.

**Comment by JoeyInvictus** [comment]
Thank you once again, @Qazeer , for your excellent suggestions. We have decided to incorporate depth settings into all scripts that utilize the convert-to-json functionality, as it is indeed a valuable addition. Additionally, we find the Compress flag interesting and will conduct internal testing to ensure compatibility with processing tools, if it works we will implement this as well!

**Comment by invictus-ir** [comment]
New version released, which fixes this.
