### ISSUE TITLE
Get-OAuthPermissions.ps1 - Fix Encoding Problem

### ISSUE THREAD

**Issue by evild3ad** [invictus-ir/Microsoft-Extractor-Suite#21]
Hi,

the CSV output of Get-OAuthPermissions.ps1 contains weird characters when dealing with German umlauts or cyrillic characters.

Please add "-Encoding UTF8" to line 231.

`$report | Export-CSV -nti -Path "Output\OAuthPermissions\OAuthPermissions-$date.csv" --> $report | Export-CSV -NoTypeInformation -Path "Output\OAuthPermissions\OAuthPermissions-$date.csv" -Encoding UTF8`

Thank you!

BR

**Comment by JoeyInvictus** [comment]
Thank you for your feedback. We appreciate it. We're currently working on a small update and we'll make sure to include your suggestion in it.

**Comment by JoeyInvictus** [comment]
Hello! We've incorporated your suggestion into the script, and it's now live on the main branch. If you ever have more ideas or ways we can improve, please don't hesitate to share them with us. Your feedback is greatly appreciated!
