### ISSUE TITLE
Get-MailboxAuditLog.ps1 - Fix Encoding Problem

### ISSUE THREAD

**Issue by evild3ad** [invictus-ir/Microsoft-Extractor-Suite#23]
Hi Joey,

the CSV output of Get-MailboxAuditLog.ps1 contains also weird characters when dealing with German umlauts or cyrillic characters.

Please add "-Encoding UTF8" to "Export-CSV" in lines 73, 87 and 99.

It seems that you can add it to all Export-Csv commands in all of your scripts.

Thank you!

BR

**Comment by JoeyInvictus** [comment]
Thank you once again, @evild3ad, for your suggestions. We'll incorporate this change into all the export-csv commands within our script and aim to implement the update this week.

**Comment by evild3ad** [comment]
Awesome! Thanks!

**Comment by JoeyInvictus** [comment]
Hi @evild3ad, we have updated the Extractor Suite. We've added the -Encoding UTF8 option to all Export-CSV commands. If you have any further suggestions, please don't hesitate to let us know.
