### ISSUE TITLE
[Feature Request] - Enrich OAuthPermissions with additional data

### ISSUE THREAD

**Issue by evild3ad** [invictus-ir/Microsoft-Extractor-Suite#24]
Hi,

may you enrich the OAuthPermissions CSV output with additional data like seen in the Azure Portal ("App registrations" and "Enterprise applications").

Following properties would be helpful to identify suspicious apps:
- Homepage URL
- AppId
- Create On

`Get-AzureADServicePrincipal -All:$true | Where-Object {$_.Tags -eq "WindowsAzureActiveDirectoryIntegratedApp"}`  

I don't know where to find the "Create On" property....possibly only available via Microsoft Graph.

Thank you!

BR

P.S. Here are some helpful links:
https://gist.github.com/TiloGit/33e95c5afe3acfc959e953db532abc72
https://gist.github.com/svarukala/64ade1ca6f73a9d18236582e8770d1d4

**Comment by JoeyInvictus** [comment]
Your suggestions are great, and we really appreciate your input! Right now, we're quite busy with holidays and other projects. If you have the time and inclination, please go ahead and submit a Pull Request. If not, no worries; we'll definitely implementing your idea later because it's a valuable addition to the script. Thanks again!

**Comment by evild3ad** [comment]
No hurry! Enjoy your holidays. When I find the time I will have a look...thx!

**Comment by JoeyInvictus** [comment]
Hi, I'd like to provide you with an update on our progress. We are working on this, but we need some more testing to do.

We have added the following key properties:
- AppId
- IsEnabled
- Description
- CreationTimestamp
- Homepage URL
- PublisherName
- ReplyUrls

**Comment by JoeyInvictus** [comment]
Hi @evild3ad, We've successfully rolled out the update to the main branch. If you have any more suggestions or improvements regarding the OAuthPermissions, please feel free to reopen this issue.

Thanks again!
