### ISSUE TITLE
[Feature Request] Provide the option to output to a specific directory

### ISSUE THREAD

**Issue by wgadzins** [invictus-ir/Microsoft-Extractor-Suite#27]
Hi,

It would be great to add a flag to specify to which directory the various commands should output, instead of within the script's base directory. 

I've tried to make a few modifications personally but have yet to come up with a functional implementation

**Comment by JoeyInvictus** [comment]
Hello, thank you for the suggestion. We'll be incorporating this in the upcoming minor patch.

**Comment by JoeyInvictus** [comment]
Hi, I wanted to let you know that all our functionalities now include the "-OutputDir" flag. This enhancement enables you to designate the directory where the different commands should output their results. If you have any other suggestions or improvements, please don't hesitate to reach out. Thank you!
