### ISSUE TITLE
[Feature Request] Check for required permission (Audit Logs)

### ISSUE THREAD

**Issue by evild3ad** [invictus-ir/Microsoft-Extractor-Suite#31]
Hi Joey,

may you add some checks for the required permission to access the audit logs?

- Get-UALStatistics.ps1 (Search-UnifiedAuditLog)
- Get-UAL.ps1 (Search-UnifiedAuditLog)
- Get-AdminAuditLog.ps1 (Search-AdminAuditLog)

With something like this...not tested...

```
try {
    $tryPermission = Search-UnifiedAuditLog -UserIds $UserIds -StartDate $currentStart -EndDate $currentEnd -ResultSize 1 -ErrorAction Stop
}
catch {
    write-logFile -Message "[WARNING] You do no not have the required permission to extract the Microsoft 365 Unified Audit Logs. Please add 'View-Only Audit Logs' role on https://admin.exchange.microsoft.com" -Color "Red"
    break
}
```

I think that would be helpful for a lot of users to identify the issue.

Thank you!

**Comment by JoeyInvictus** [comment]
Thank you for the suggestion, @evild3ad. We've been thinking about improving this part for a while now. Need to find and catch all errors and display the correct error message to help the user identify the issue.

I'll make an effort to work on this when I have some free time and will keep you informed once it's completed.

**Comment by JoeyInvictus** [comment]
Hi @evild3ad,

I'll be closing this issue for the time being, please don't hesitate to reopen it if needed. Currently, identifying a specific solution is challenging as multiple errors are resulting in the same error message.
