### ISSUE TITLE
Encoding option doesn't appear to be working when providing -encoding

### ISSUE THREAD

**Issue by rocket-ops** [invictus-ir/Microsoft-Extractor-Suite#32]
Reviewing the updated issues, I saw where -encoding was added. Currently, it does not appear to work when adding any value after the -encoding switch. 

Example:

Out-File : Cannot validate argument on parameter 'Encoding'. The argument "utf8NoBOM" does not belong to the set
"unknown,string,unicode,bigendianunicode,utf8,utf7,utf32,ascii,default,oem" specified by the ValidateSet attribute.
Supply an argument that is in the set and then try the command again.
At C:\projects\tools\M365_Toolset\Microsoft-Extractor-Suite\Scripts\Get-UAL.ps1:482 char:81
+ ... Out-File -Append "$OutputDir/UAL-$sessionID.json" -Encoding $Encoding
+                                                                 ~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Out-File], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationError,Microsoft.PowerShell.Commands.OutFileCommand

**Comment by JoeyInvictus** [comment]
Hi, which version of PowerShell you are currently using?

To determine your PowerShell version, you can execute the following command in PowerShell: `$PSVersionTable`

In our testing, we found that on PowerShell version 5.1, only the values listed in the error message seem to work:
`unknown, string, unicode, bigendianunicode, utf8, utf7, utf32, ascii, default, oem`

For the `utf8NoBOM` encoding flag and some others, PowerShell version 6 or higher is required. We upgraded our PowerShell to version 7, and everything appears to be functioning as expected.
