### ISSUE TITLE
[Issue] Get-AdminAuditLog - Default: OutputAdminAuditLog is not working

### ISSUE THREAD

**Issue by evild3ad** [invictus-ir/Microsoft-Extractor-Suite#33]
I used v1.1.3 from PSGallery...Get-AdminAuditLog is not working...you need to specify -OutputDir as workaround.

![Get-AdminAuditLog](https://github.com/invictus-ir/Microsoft-Extractor-Suite/assets/8110531/2f615606-d882-4ec7-a44d-3a43d48a183d)

**Comment by evild3ad** [comment]
Get-TransportRules has nearly the same issue...specifying the -OutputDir is not working too. 

![Get-TransportRules](https://github.com/invictus-ir/Microsoft-Extractor-Suite/assets/8110531/c48cd320-b30b-491f-a6f6-ab9badeee790)

**Comment by JoeyInvictus** [comment]
Hello, we tried to replicate this error message, but both my colleague and I were unsuccessful. Our attempts included testing on a new Virtual Machine with the Extractor version 1.1.3 downloaded from the PSGallery. 

Is the problem limited to the get-transportrules and get-adminauditlog modules, or does it affect all modules? You can try to edit the get-adminauditlogs.ps1 file, specifically removing "| out-null" from line 54. Run the script afterward to see if it generates an error while creating the directory. (Don't forget to import the module again)

Would you mind attempting to uninstall and reinstall to check if that resolves the issue? Another potential reason could be that the script lacks the necessary permissions to write a file to that directory.

**Comment by evild3ad** [comment]
All other modules were working. PowerShell is running as admin and I used the same output directory for the other modules. I will do the other checks in some minutes.

**Comment by evild3ad** [comment]
Both cmdlets were working now. Strange...hm...I remember a conflict with signing in the customers tenant and signing out of my dev tenant when I tried to access the MS Teams admin center yesterday. You can close the issue. Thanks Joey!

![09-11-2023_14-57-16](https://github.com/invictus-ir/Microsoft-Extractor-Suite/assets/8110531/c2aa4e29-5119-4c9b-add2-68cb13a3d4a1)

**Comment by JoeyInvictus** [comment]
Haha, glad it's working now! If the issue resurfaces, we'll dive in to figure out the root cause.
