### ISSUE TITLE
Falure - Get-MailboxAuditLog

### ISSUE THREAD

**Issue by etaylor77** [invictus-ir/Microsoft-Extractor-Suite#35]
When attempting to get the audit logs for a user, I am getting the following error:

```
ConvertFrom-Json : Invalid JSON primitive: .
At C:\Users\<redacted>\AppData\Local\Temp\tmpEXO_3bjc2biq.vhm\tmpEXO_3bjc2biq.vhm.psm1:625 char:35
+ ... etailsToPSObject = ConvertFrom-Json $ErrorObject.ErrorDetails.Message
+                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [ConvertFrom-Json], ArgumentException
    + FullyQualifiedErrorId : System.ArgumentException,Microsoft.PowerShell.Commands.ConvertFromJsonCommand
```

**Comment by JoeyInvictus** [comment]
Hi,

Could you provide the specific command, along with any parameters or flags, that you're attempting to execute? The 'Get-MailboxAuditLog' command doesn't utilize the 'ConvertFrom-Json' function, as it exclusively supports output in CSV format. I'm uncertain about the cause of this error, and additionally, I'm unable to replicate it in our test environment.

**Comment by etaylor77** [comment]
Thanks for the response. I tried to keep these simple and following your docs. Here is the command:

`Get-MailboxAuditLog -StartDate 1/1/2023 -EndDate 1/01/2024`

**Comment by JoeyInvictus** [comment]
Could you possibly test this on a different machine, perhaps a virtual machine? We haven't made recent changes to this module and haven't encountered this issue ourselves, nor have we received similar feedback. Unfortunately, I'm unable to replicate the error in our test environment.

**Comment by etaylor77** [comment]
Sure, give me a bit. I am seeing other weird messages about needing to make a GraphAPI call before executing the command.

**Comment by JoeyInvictus** [comment]
Hi, let me know if there is anything we can support you with. The Get-MailboxAuditLog command shouldn't use GraphAPI calls.

**Comment by JoeyInvictus** [comment]
Hello, I'm going to mark this issue as closed for the time being. However, if you're still experiencing difficulties, or if you come across any new issues, please don't hesitate to reopen it. Your input is valuable in ensuring everything is operating smoothly.
