### ISSUE TITLE
Failure - Get-Email

### ISSUE THREAD

**Issue by etaylor77** [invictus-ir/Microsoft-Extractor-Suite#36]
I was really eager to try out this new addition to the module. 

I am running the following command to connect to Graph API:

`Connect-MgGraph -Scopes Mail.ReadBasic.All`

This seems to connect fine once I grant the permissions. I then run the following command:

`Get-Email -userIds "<redacted>" -internetMessageId "<0100018c6ed66a38-0349599a-2f53<redacted>>" -attachment True`

This generates the following error:

```
Connect-MgGraph : InteractiveBrowserCredential authentication failed: AADSTS650053: The application 'Microsoft Graph Command Line Tools' asked for scope 
'Mail.ReadBasic.All' that doesn't exist on the resource '00000003-0000-0000-c000-000000000000'. Contact the app vendor. Trace ID: 
630903eb-3f8e-4646-ad60-28456c001400 Correlation ID: 46d1a63e-c0e3-4703-9787-ca2db26365e6 Timestamp: 2024-01-17 02:55:46Z
At line:1 char:1
+ Connect-MgGraph -Scopes Mail.ReadBasic.All
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Connect-MgGraph], AuthenticationFailedException
    + FullyQualifiedErrorId : Microsoft.Graph.PowerShell.Authentication.Cmdlets.ConnectMgGraph
 
```

**Comment by JoeyInvictus** [comment]
Hi, 

Unfortunately, the 'Mail.ReadBasic.All' permission are classified as application permissions, which means they cannot be utilized as delegated permissions. Did you authenticate as an application?

`Allows the app to read basic mail properties in all mailboxes without a signed-in user. Includes all properties except body, previewBody, attachments and any extended properties.`

You can utilize the 'Mail.ReadBasic' permission to access emails in the mailbox of the user who is currently signed in. However, to read emails in other users' mailboxes, the 'Mail.ReadBasic.All' permission is required.

This can be achieved by registering an application in Azure and assigning the necessary Graph API permissions/scopes. Once registered, you can log in using the application credentials with the following steps:

Step 1: Create a ClientSecretCredential object with your App/Client ID:
$ClientSecretCredential = Get-Credential -Credential {App/Client Id}

Step 2: Connect to the Graph API using your Tenant ID and the ClientSecretCredential:
Connect-MgGraph -TenantId {TenantId} -ClientSecretCredential $ClientSecretCredential"

**Comment by JoeyInvictus** [comment]
Hello, I'm going to mark this issue as closed for the time being. However, if you're still experiencing difficulties, or if you come across any new issues, please don't hesitate to reopen it. Your input is valuable in ensuring everything is operating smoothly.
