### ISSUE TITLE
[Feature Request] Add UserIds parameter to both ADSignInLogs acquisition methods

### ISSUE THREAD

**Issue by evild3ad** [invictus-ir/Microsoft-Extractor-Suite#37]
Please add -UserIds parameter (like seen in UAL) to Get-ADSignInLogs and Get-ADSignInLogsGraph. This filter would be very helpful in an investigation when a M365 user account is suspected as compromised. I had the case that both API's failed with an "Out of memory" error message...may happen when it is an big tenant with a lot of users. Thanks!

**Comment by JoeyInvictus** [comment]
Hi, we are happy to incorporate this feature when we  have some available time.

**Comment by JoeyInvictus** [comment]
Hi, I've updated the development branch of our repository adding the -UserIds parameter to both the Get-ADSignInLogs and Get-ADSignInLogsGraph functions. Let me know what you think!

**Comment by evild3ad** [comment]
You are too fast! ;-)

I will test it tomorrow. Thanks a lot!

**Comment by JoeyInvictus** [comment]
I have merged the development branch into the main branch. If you encounter any issues or notice anything missing, please feel free to reopen this issue :)!
