### ISSUE TITLE
Silly json question... how do I read this json? 

### ISSUE THREAD

**Issue by mathurin68** [invictus-ir/Microsoft-Extractor-Suite#38]
This looks SUPER useful but....
If I run 

Get-ActivityLogs -StartDate 2024-01-23

it gives me a couple files that are supposed to be json, and I don't have a lot of json experience, but it's unlike any json I've ever seen.  There's no {} or anything.  

Is there a trick to read this, or convert to a dataframe or csv? 

Thanks!  And thanks for creating these!!

**Comment by invictus-korstiaan** [comment]
Hi there, thank you for trying out our tool. The output of most commands will be .json files and they are all valid json. You can validate the file with a tool like jsonlint. 
However, the more interesting part is how can you analyze this and most people use something like Elastic/SOF-ELK as open-source tool to load these files in. If you have a license you can also use commercial tools like Splunk for analysis.

**Comment by mathurin68** [comment]
Got it...I will spin SOF-ELK(love it) up and give it a shot, thank you for your answer!!
