### ISSUE TITLE
Get-MessageIDs - Parameter SessionID errors as code use parameter -Sessions

### ISSUE THREAD

**Issue by TimberJank** [invictus-ir/Microsoft-Extractor-Suite#47]
In the current documentation when running Get-MessageIDs with -SessionID it errors out stating 'A parameter cannot be found that matches parameter name 'SessionID'.

Based on the code the actual parameter is 'Sessions'. Could we fix it so its SessionID?

<img width="299" alt="image" src="https://github.com/invictus-ir/Microsoft-Extractor-Suite/assets/66707167/58bd9fee-92c8-45db-8788-0f804138087d">

Not a big issues but thanks for fixing!

**Comment by JoeyInvictus** [comment]
Hi, thank you for pointing that out. It seems like we lost a change while pushing the new version since we had fixed this one earlier. We did change the name in the ReadTheDocs documentation to "Sessions," as this is the correct one.
