### ISSUE TITLE
Azure Activity Logs - JSON Export not in JSON

### ISSUE THREAD

**Issue by angry-bender** [invictus-ir/Microsoft-Extractor-Suite#48]
**Problem**
`Get-ActivityLogs` not outputting in expected JSON format, appears ti be outputting as a PowerShell List

**Sample (First 30 lines of output from TenantID-ActivityLog.json (From a test tenant)**

`

Authorization        : 
                       Scope     : /subscriptions/9d797f5b-50ed-495e-ab5c-73e4cb4e6b0c/resourceGroups/dfir-log-retentio
                       n/providers/microsoft.network/virtualNetworks/storage/taggedTrafficConsumers/Microsoft.Storage.e
                       astus.slice3.instance9
                       Action    : microsoft.network/virtualNetworks/taggedTrafficConsumers/delete
                       Role      : 
                       Condition : 
Claims               : 
                       aud            : https://management.core.windows.net/
                       iss            : https://sts.windows.net/aec7fc6e-8410-42d4-a80f-bde141f94779/
                       iat            : 1708478526
                       nbf            : 1708478526
                       exp            : 1708565226
                       aio            : E2NgYNAPPuNquz90jbjD/116Z7trAA==
                       appid          : a6aa9161-5291-40bb-8c5c-923b567bee3b
                       appidacr       : 2
                       http://schemas.microsoft.com/identity/claims/identityprovider: 
                       https://sts.windows.net/aec7fc6e-8410-42d4-a80f-bde141f94779/
                       idtyp          : app
                       http://schemas.microsoft.com/identity/claims/objectidentifier: 
                       848016a8-00f9-448f-8a8b-eaddbd1c6565
                       rh             : 0.AagAbvzHrhCE1EKoD73hQflHeUZIf3kAutdPukPawfj2MBPzAAA.
                       http://schemas.xmlsoap.org/ws/2005/05/identity/claims/nameidentifier: 
                       848016a8-00f9-448f-8a8b-eaddbd1c6565
                       http://schemas.microsoft.com/identity/claims/tenantid: aec7fc6e-8410-42d4-a80f-bde141f94779
                       uti            : y0ATnSu0vEmRgJMLxB6bAA
                       ver            : 1.0
                       xms_cae        : 1
                       xms_tcdt       : 1707439034`
                       
**Expected Behavior**    

Extracted JSON file is output in a JSON format, rather than the default PStable output from `Get-AzActivityLog`

**Troubleshooting**    

Its appears this is the same output as the default from `Get-AzActivityLog`

Based on this, in my own code, I placed the default output from `Get-AzActivityLog` in a object, then converted to JSON.

**Comment by JoeyInvictus** [comment]
Thank you for the explanation. We appreciate your efforts in submitting the pull request, and we've accepted it :)!
