### ISSUE TITLE
Provide an Option for JSON

### ISSUE THREAD

**Issue by joshlemon** [invictus-ir/Microsoft-Extractor-Suite#5]
Provide the ability to output the collected UAL in a JSON formatted file.

This will also allow for ingestion via SOF-ELK.

**Comment by invictus-ir** [comment]
Good suggestion, currently testing this feature. Should be added added in the coming weeks.

**Comment by invictus-ir** [comment]
Please update and you'll be able to use this feature in the different functions. For example:
Get-UALAll -Output json will grab the full UAL and save it as json files.
