### ISSUE TITLE
Get-ADSignInLogs and Get-ADAuditLogs Commandlets Not Working

### ISSUE THREAD

**Issue by n2x4** [invictus-ir/Microsoft-Extractor-Suite#6]
Attempting to leverage the Get-ADSignInLogs and Get-ADAuditLogs commands results in an error specifying that you must call connect-azure first (see screenshot).

Connect-azure runs as expected, and I'm able to authenticate, however attempting to use these two Azure AD functions error out. Get-OAuthPermissions works as expected.

![image](https://user-images.githubusercontent.com/31667936/234413996-92508817-85ba-44b9-9063-94cc9bdf9b9d.png)

**Comment by JoeyInvictus** [comment]
Hi,

This appears to be a known issue that arises when installing AzurePreview on a system where AzureAD is already installed. To check if the AzureADPreview module is installed, you can run the 'get-module' PowerShell cmdlet.

![image](https://user-images.githubusercontent.com/129975292/234500190-8dbfd916-3b8e-4d2e-9bfc-4deb1e1030fb.png)

If the AzureADPreview module is installed, but the error persists, the recommended solution is to uninstall the AzureAD module and keep only the AzureADPreview module installed. The cmdlets that are being used are currently only available in the Preview module.

The Get-ADSignInLog function uses the PowerShell cmdlet `Get-AzureADAuditDirectoryLogs`. It might be worth running this cmdlet separately to determine if the error message persists. Additionally, you can run the command `Get-Module AzureADPreview -ListAvailable | % { $_.ExportedCommands.Values }` to check if 'Get-AzureADAuditDirectoryLogs' and 'Get-AzureADAuditDirectoryLogs' are being imported correctly.

**Comment by n2x4** [comment]
Yep, you're right! I saw that the logic check to the connection was just running the "Get-AzureADAuditSignInLogs". Running that command alone returned an error that the command was not recognized. I reviewed the installed modules and saw that the AzureAD module was not the preview one. I was fixated on the "must call connect-azure" error and didn't relate it to a module issue.
