### ISSUE TITLE
Missing data in the “Amount of log entries” CSV collumn of Get-UALStatistics

### ISSUE THREAD

**Issue by Camel0101** [invictus-ir/Microsoft-Extractor-Suite#65]
Hello,
I noticed that when running the “Get-UALStatistics” command, the output CSV collumn “Amount of log entries” is empty. When you go to the location in the script where it adds the results to the CSV, the “$number” variable is supposed to represent the number of logs.
```powershell
	Foreach ($record in $recordTypes) {
		$specificResult = Search-UnifiedAuditLog -Userids $UserIds -StartDate $script:StartDate -EndDate $script:EndDate -RecordType $record -ResultSize 1 | Select-Object -First 1 -ExpandProperty ResultCount
		if ($specificResult) {
			Write-LogFile -Message "$($record):$($specificResult)"
			Write-Output "$record,$number" | Out-File $outputDirectory -Append
		}
		else {
		}
	}
```
By changing variable “$number” to “$specificResult” in this [line](https://github.com/invictus-ir/Microsoft-Extractor-Suite/blob/eaa7badee6479e18bcc745fa92484f006e262210/Scripts/Get-UALStatistics.ps1#L92) , we get the number of logs for each record type in the CSV as expected.

**Comment by JoeyInvictus** [comment]
Hi, thanks a lot for pointing this out. I'm not sure what happened and why it broke. Will fix it in next update!

**Comment by JoeyInvictus** [comment]
We just released the update to fix this. Feel free to reopen the issue if it doesn't work as expected.
