### ISSUE TITLE
Docs type-o creates a long night (Get-MessageIDs Get-Sessions -StartDate 1/4/2023 -EndDate 5/4/2023 -IP 1.1.1.1)

### ISSUE THREAD

**Issue by GrumpyLT** [invictus-ir/Microsoft-Extractor-Suite#66]
Docs says:
Collects all sessions for the IP address 1.1.1.1.

Get-MessageIDs Get-Sessions -StartDate 1/4/2023 -EndDate 5/4/2023 -IP 1.1.1.1

If someone doesnt realize Get-Sessions isnt suppose to be there, they could waste 3 beers troubleshooting.......

All joking aside, you guys/gals are great, keep up the good work, just please fix the type-o

**Comment by JoeyInvictus** [comment]
Haha, thanks for pointing this out! We did make the change in our stashed changes, and it will be fixed in our next update. If you have any other improvements we can make, please let us know, and we'll try to incorporate those as well.
