### ISSUE TITLE
Use of Break Statement in Try Catch

### ISSUE THREAD

**Issue by angry-bender** [invictus-ir/Microsoft-Extractor-Suite#80]
Hi Again,

Looks like if you have a wrapper script, any `break` functions like that in Get-RiskyEvents will also break out of the parent scripts try catch :-).

No Biggie, but for PowerShell, as your not inside a loop for a lot of these functions, an `throw` should be fine instead of a `break` https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_throw?view=powershell-7.4 . This will help for any wrapper scripts in future releases if you choose to use a try catch there :-)

Would be good to review each of your try catches to change them to a `throw` if not in a loop, I'll flick one accross shortly in #79

**Comment by JoeyInvictus** [comment]
Thanks, I was not aware of this good suggestion and thanks for the Pull request. :)!
