### ISSUE TITLE
Update to 2.0.2

### ISSUE THREAD

**Issue by ForeGuards** [invictus-ir/Microsoft-Extractor-Suite#84]
HI,

I have just updated my repo, and even on version 2.0.2, the import module still requests to update to 2.0.2 (please check the attachment):
![2 0 2](https://github.com/user-attachments/assets/784068ac-ae6d-405d-a12d-148d2f575b87)

Thanks and cheers
Giuseppe

**Comment by JoeyInvictus** [comment]
Hi!

I tried to reproduce it, but it seems to work for both me and someone else. (Also made evild3ad try it, you might know him;))

Can you run `Get-Module` and see which modules are imported? It might be that an old version is still loaded.

![image](https://github.com/user-attachments/assets/17549f33-8bce-4753-a06b-c56410d051e4)

**Comment by ForeGuards** [comment]
Yeah, I know him well. :) I rebooted the server, downloaded a brand new version from Github, and did the following from the screenshot. 
![CleanShot 2024-07-24 at 16 08 35](https://github.com/user-attachments/assets/9f438193-5aa1-48cd-bbfa-c23b1b4c3161)

But, easy is not that urgent. We could close the issue. I just wanted to let you know.

**Comment by ForeGuards** [comment]
solved!
