### ISSUE TITLE
Azure Directory Activity Logs donw show

### ISSUE THREAD

**Issue by kinomakino** [invictus-ir/Microsoft-Extractor-Suite#86]
First of all, thanks for the help.
I'm trying out the tool, and I'd like to get the log of an ADFS server from Azure Directory Activity Logs like I do with AADinternals (Get-AADIntAzureDirectoryActivityLog) and it doesn't appear.

Do you have any evidence that it's downloading these events? I'm looking for this one: /providers/Microsoft.ADHybridHealthService

Thanks for the effort of the tool.

![Captura de pantalla 2024-09-07 a las 11 47 49](https://github.com/user-attachments/assets/e7658ad1-858c-4a49-942f-23c5e7119cc7)

**Comment by JoeyInvictus** [comment]
Hi, 

Did you run `Get-DirectoryActivityLogs`, this one should get all the Directory Activity Logs. The output should be written to the output directory.

**Comment by kinomakino** [comment]
Thanks for your interest.
The events for Listing servers appear, but not the events for creating or updating servers.
I've been looking at the id_correlation and these events don't appear.
With AAdInternals they do appear, I mean, it's something in your extraction process. Maybe when you create the CSV there's some "where" or something that doesn't show them.
I'll send you a CSV from yesterday and today.

I am sending you the screenshot where the event appears: LIST with the correlation id 0123b224-0a59-427e-b74d-1e361d887ae9 that does appear in the csv of your tool

***@***.***

and I am sending you a screenshot with the Create Server with the correlation id that I cannot find in your csv
f3bf7bc9-c028-4e88-b360-fe0111193531


***@***.***

Maybe I'm making a mistake, or maybe it's something with the dates, but I've tried with 31 days and that didn't work either.

Thanks for everything, especially for the great work you do with this great tool.

Regards

De: JoeyInvictus ***@***.***>
Fecha: sábado, 7 de septiembre de 2024, 15:41
Para: invictus-ir/Microsoft-Extractor-Suite ***@***.***>
CC: kinomakino ***@***.***>, Author ***@***.***>
Asunto: Re: [invictus-ir/Microsoft-Extractor-Suite] Azure Directory Activity Logs donw show (Issue #86)

Hi,

Did you run Get-DirectoryActivityLogs, this one should get all the Directory Activity Logs. The output should be written to the output directory.

**Comment by JoeyInvictus** [comment]
Hi, I pushed some changes to the GitHub project. Can you download the repository, import the module, and try again? I haven't pushed the update to the PowerShell Gallery yet. I want to make sure it solves your issues before pushing the update to all platforms.

**Comment by JoeyInvictus** [comment]
Hi, did you manage to test this?
