### ISSUE TITLE
Get-UALSpecifivcActivity Erroring on null splat

### ISSUE THREAD

**Issue by wgadzins** [invictus-ir/Microsoft-Extractor-Suite#88]
Line 859 was modified to add "@baseQuerySearch" but the function doesn't identify that as a parameter (does in other functions) 

it errors with "Search-UnifiedAuditLog : A positional Parameter cannot be found that accepts argument '$null'"

Going to test adding it and will propose change if I get it working properly

**Comment by JoeyInvictus** [comment]
Hi, thanks. Looks like I broke `Get-UALSpecificActivity` while adding the `ObjectIDs` field to the different UAL acquisition methods. So it should still work in the `2.0.2` version on the Gallery and Release page and only cause errors in the one on the GitHub repository.

I pushed the updated code fixing your issue to GitHub. Feel free to let me know if it works :)

**Comment by wgadzins** [comment]
Incredible turnaround - pulled a copy and was testing changes when I couldn't find the splat, right on! Testing live version now

**Comment by JoeyInvictus** [comment]
Haha, I will close the ticket. Let me know if you have any other suggestions or improvements; feel free to reopen it.
