### ISSUE TITLE
AzureAD and AzureADPreview modules set to be deprecated

### ISSUE THREAD

**Issue by LucioBenzor** [invictus-ir/Microsoft-Extractor-Suite#9]
Saw that the AzureADPreview modules that this suite uses are slated to be replaced by the Graph Powershell Module. Any plans to migrate in the coming months to that module?

Source: https://learn.microsoft.com/en-us/powershell/module/azuread/?view=azureadps-2.0

**Comment by invictus-ir** [comment]
Hi Lucio, 

Thank you for your comment. We'd love to upgrade to the new modules, but I haven't seen a Graph PowerShell module for this purpose. If we have overlooked it, please let us know and we will implement asap.
