### ISSUE TITLE
Invoke-MgGraphRequest : Too many retries performed. More than 3 retries encountered while sending the request.

### ISSUE THREAD

**Issue by hodf-cye** [invictus-ir/Microsoft-Extractor-Suite#90]
Hey,
It's my first time when I'm trying to get logs using the Get-UALGraph command.
At first I was getting 500 response from microsoft and now I'm just getting "Invoke-MgGraphRequest : Too many retries performed. More than 3 retries encountered while sending the request".

This is the command I've used:
Get-UALGraph -SearchName test3 -startDate "2024-09-16T10:18:37Z" -endDate "2024-09-17T10:18:37Z"

I'm using the latest versions of Microsoft.Graph and Microsoft-Extractor-Suite

Thanks

**Comment by JoeyInvictus** [comment]
Hi! Unfortunately, the Graph UAL part is quite buggy at the moment, and there are some known issues with the MS backend. However, for this issue, it might be the problem that you're only allowed to run a limited number of scans simultaneously. So you have to wait for one to finish before starting a new one.

You can list the current scans and see there status by running:
`Get-MgBetaSecurityAuditLogQuery | fl *`

![image](https://github.com/user-attachments/assets/e66a97f5-4615-482b-a190-308b4cfa2635)

It seems like an issue with `Invoke-MgGraphReques`t, which is a cmdlet by Microsoft used by the Extractor Suite to make calls to start the scan, get the scan status, and download the results when it's done. I haven't heard of this issue before for the Graph UAL part, but if the above isn't the cause, I will try to reproduce it and see how to fix it.
