### ISSUE TITLE
Get-MessageIds -Download switch creates a folder using the provided value

### ISSUE THREAD

**Issue by SecurityAura** [invictus-ir/Microsoft-Extractor-Suite#92]
Running on the latest v2.0.3 that was just released. Not sure if it's intended or not but, using the Get-MessageIds cmdlet with the -Download switch set to "Yes", literally creates the folder with that name.

![image](https://github.com/user-attachments/assets/9d531ac3-b875-4a50-a0c1-7a7d53603ff3)

I tested using another value to make sure.

![image](https://github.com/user-attachments/assets/65c83ee6-1bd3-460f-a932-e5259711d03d)

I'm guessing the expected behavior here is:

-Download should only accept "Yes" or "No", with "No" being the default (as documented)
-OutputDir, if specified will create the dir in which the downloaded emails will be located. Otherwise, use the default value (as documented)

https://microsoft-365-extractor-suite.readthedocs.io/en/latest/functionality/MailItemsAccessed.html

On a side note, since -Download is now available for Get-MessageIds and it relies on access to GraphAPI, may be worth adding the same disclaimers/instructions regarding connecting to MgGraph with the right scope to that cmdlet documentation page, like it's the case for the Get-Email and Get-Attachment cmdlet.

https://microsoft-365-extractor-suite.readthedocs.io/en/latest/functionality/GetEmails.html

**Comment by JoeyInvictus** [comment]
Hi, sorry, my mistake. I just made `-Download` a switch parameter so it aligns with the rest of the parameters used in the different functions, like `-MergeOutput`. Now, you just need to use `-Download` to download the files, no more true/false or yes/no behind it to make it more clean.

`Get-MessageIDs -StartDate "2024-01-01" -EndDate "2024-09-24" -Download -IP 10.11.12.13`

When no parameter is provided, it will assume you're trying to specify the `OutputDir` parameter, creating the output directory if it doesn't exist. I'll see if I can fix this in the next update.

I like the suggestion of adding the Graph API warning/instructions. I think that would be a good idea. I'll add this in the next update!

**Comment by SecurityAura** [comment]
Ahhh okay! So once again, I just misunderstood the instructions it's my bad! Thanks for the explanation :)

Speaking of -MergeOutput, would it be possible to add it for: Get-UALSpecificActivity?

I used it recently on an IR to get the UserLoggedIn events for all the users. Ended up merging the resulting CSVs together at the end manually but I'm guessing -MergeOutput could handle it. It's supported for the other three (3) UAL cmdlet already.

**Comment by JoeyInvictus** [comment]
No worries! I'll add the `-MergeOutput` option to `Get-UALSpecificActivity` as well. I often wonder if people are really using some of the extractor’s functions, like `Get-MessageIds` and `Get-UALSpecificActivity`so I do less development in those areas, but I guess I’ve just found someone who uses both, haha.

Since it’s easy to add, I’ll definitely include it in the next update!

**Comment by SecurityAura** [comment]
I'm definitely the kind of user that will try to use even the less known/popular functions for ... reasons haha!

Currently working on wiping up a script that uses Get-Email to download emails from an Internet Message Ids list provided in input.

If you were looking for your next enhancement for the module to support that natively! :P

**Comment by JoeyInvictus** [comment]
`Get-email` has the `-inputFile` parameter:
_The inputFile parameter specifies the .txt file containing multiple Internet Message Identifiers. You can include multiple Internet Message Identifiers in the file. Ensure each ID is placed on a new line._

Is this what you looking for ^^? Or do I have extra work to do.

**Comment by SecurityAura** [comment]
I need to learn to RTFM hahaha! Exactly what I'm looking for, thank you!

We can go ahead and close this issue before I start asking more questions that could be answered by just using my eyes 🤣

**Comment by JoeyInvictus** [comment]
Haha, it happens to the best of us! I've added so many options and feature requests over time that I can’t keep track of them myself anymore. Feel free to reopen or create a new issue if you have any additional questions or suggestions. ;)

**Comment by JoeyInvictus** [comment]
FYI, pushing the following two requested options to the project now :)

```
Added -mergeoutput flag to Get-UALSpecificActivity, as suggested by @SecurityAura.
Added a warning when using the -Download flag in Get-MessageIDs without an active Graph connection, also as suggested by @SecurityAura.
```
