### ISSUE TITLE
Show-MailboxRules fails in 2.0.3

### ISSUE THREAD

**Issue by Hacks4Packs** [invictus-ir/Microsoft-Extractor-Suite#93]
PS C:\Users\XYZ> Show-MailboxRules -UserIds "someone@redacted.com"

[INFO] Checking someone@redacted.com...
Get-InboxRule: []\PowerShell\Modules\Microsoft-Extractor-Suite\2.0.3\Scripts\Get-Rules.ps1:153
Line |
 153 |              $inboxrule = get-inboxrule -Mailbox $UserIds
     |                                         ~~~~~~~~
     | A parameter cannot be found that matches parameter name 'Mailbox'.

**Comment by JoeyInvictus** [comment]
Hi, weird one so `get-inboxrule -Mailbox` command is used by the Extractor Suite to lookup the mailbox rules. However, it's odd that it’s returning an error stating that the "Mailbox" parameter cannot be found.

![image](https://github.com/user-attachments/assets/7c3544dd-2348-49ff-aa0a-563419754d5f)

It seems to be working fine on my end. Could you try running the following command to bypass the Extractor Suite and help identify the underlying issue? (replace the email with one in your domain)

`Get-InboxRule -Mailbox Joe@Contoso.com`

![image](https://github.com/user-attachments/assets/a4eb5fa5-3eb3-447b-a392-71355104b97b)

**Comment by Hacks4Packs** [comment]
Does look like a "me" issue - I'll nuke and rebuild my ExchPowershell install. 

PS C:\Users\XYZ> get-inboxrule -Mailbox Bleh@..
Get-InboxRule: A parameter cannot be found that matches parameter name 'Mailbox'.


Get-Help Get-Inboxrule
NAME
    Get-InboxRule
SYNOPSIS
    This cmdlet is available in on-premises Exchange and in the cloud-based service. Some parameters and settings may be exclusive to one environment or the
    other.

    Use the Get-InboxRule cmdlet to view Inbox rule properties. Inbox rules are used to process messages in the Inbox based on conditions specified and take
    actions such as moving a message to a specified folder or deleting a message.

    For information about the parameter sets in the Syntax section below, see Exchange cmdlet syntax
    (https://docs.microsoft.com/powershell/exchange/exchange-cmdlet-syntax).

SYNTAX
    Get-InboxRule [[-Identity] <InboxRuleIdParameter>] [-BypassScopeCheck] [-DescriptionTimeFormat <String>] [-DescriptionTimeZone <ExTimeZoneValue>]
    [-IncludeHidden] [-Mailbox <MailboxIdParameter>] [<CommonParameters>] <-------?!?!

**Comment by JoeyInvictus** [comment]
Haha finally it's not me. Let me know if there is anything I can help with.
