### ISSUE TITLE
Get-AdSignInLogsGraph

### ISSUE THREAD

**Issue by angry-bender** [invictus-ir/Microsoft-Extractor-Suite#95]
#Problem
When using Get-ADSignInLogsGraph with a custom start and end time, percent complete preents an error

```
[ERROR] An error occurred: Cannot validate argument on parameter 'PercentComplete'. The -7 argument is less than the minimum allowed range of -1. Supply an argument that is greater than or equal to -1 and then try the command again.
```

##Workaround
Remove all percentage Complete functions

**Comment by JoeyInvictus** [comment]
What command are you running? I am trying to reproduce the error, but when I provide a custom end date, start date, or both, it seems to work fine for me. However, I only have 624 events in the test environment, so that might be why it works for me.

![image](https://github.com/user-attachments/assets/8866dd31-74dc-4502-b417-36191e68a941)

**Comment by angry-bender** [comment]
> What command are you running? I am trying to reproduce the error, but when I provide a custom end date, start date, or both, it seems to work fine for me. However, I only have 624 events in the test environment, so that might be why it works for me.
> 
> ![image](https://github.com/user-attachments/assets/8866dd31-74dc-4502-b417-36191e68a941)
> 

Weird I ran the same as your second one with start and end date, do you have more than one odata stream in that small tenancy?

**Comment by JoeyInvictus** [comment]
Yeah, I guess that might be the issue. I'll write a script to generate some login events in the environment, haha.

**Comment by JoeyInvictus** [comment]
Okay, I’m not entirely sure why, but it still works for me😅. So, just to confirm, removing the following lines makes it work for you, right?


```
$TotalTicks = ($script:EndDate-$script:StartDate).Ticks
$progress = [Math]::Round(($script:EndDate-$from).Ticks / $TotalTicks * 100, 2)
Write-Progress -Activity "Collecting Sign-in logs" -Status "$progress% Complete" -PercentComplete $progress
```

If that's the case, I might temporarily remove it since I'm going on holiday on Monday and don't want more issues haha. I'll look into it in more detail once I'm back.

![image](https://github.com/user-attachments/assets/db90c75b-e8e2-4959-8818-7e5ead30ad85)

**Comment by angry-bender** [comment]
> Okay, I’m not entirely sure why, but it still works for me😅. So, just to confirm, removing the following lines makes it work for you, right?
> 
> 
> ```
> $TotalTicks = ($script:EndDate-$script:StartDate).Ticks
> $progress = [Math]::Round(($script:EndDate-$from).Ticks / $TotalTicks * 100, 2)
> Write-Progress -Activity "Collecting Sign-in logs" -Status "$progress% Complete" -PercentComplete $progress
> ```
> 
> If that's the case, I might temporarily remove it since I'm going on holiday on Monday and don't want more issues haha. I'll look into it in more detail once I'm back.
> 
> ![image](https://github.com/user-attachments/assets/db90c75b-e8e2-4959-8818-7e5ead30ad85)
> 

Those were the ones I removed, I'd be happy to keep as is, might have been this tenancy (there was a unicode emoji in some of my logs, that likes to throw things 🤣)

**Comment by JoeyInvictus** [comment]
Haha guess your next question is going to be to add support for emojis in the logs haha

**Comment by angry-bender** [comment]
> Haha guess your next question is going to be to add support for emojis in the logs haha

Ha it's doesn't happen often, I think it's just a change from utf-8 if memory serves me correctly, let me check

**Comment by angry-bender** [comment]
> > Haha guess your next question is going to be to add support for emojis in the logs haha
> 
> Ha it's doesn't happen often, I think it's just a change from utf-8 if memory serves me correctly, let me check

There we go utf-16le https://github.com/iandday/o365AuditParser/issues/1
