### ISSUE TITLE
Get-UalGraph - DateType Issue

### ISSUE THREAD

**Issue by angry-bender** [invictus-ir/Microsoft-Extractor-Suite#96]
Same as #76 

Attempting to apply the same fix for the following JSON objects

$_.CreatedDateTime
$_.auditData.CreationTime

There may be some more, but this might give a start

**Comment by angry-bender** [comment]
Fixed, added to PR

**Comment by JoeyInvictus** [comment]
Hi, thanks. Let me check it out. On a side note, regarding issue [75](https://github.com/invictus-ir/Microsoft-Extractor-Suite/issues/75), is it still broken for larger UAL acquisitions? I only had access to some smaller environments, so I was not able to test it properly last month.

**Comment by angry-bender** [comment]
Unfortunately I haven't had one to test, just had small ones in the meantime too 😞

**Comment by JoeyInvictus** [comment]
Thanks, I'll close the issue for now. Feel free to reopen it or create a new one. I will also take a look at the other one today.
